### PR TITLE
Add photo options

### PR DESCRIPTION
**Pull request by acapro**
when a photo in the wysiwyg editor is clicked, photo options appear
allowing for normal or wrapped class, and setting an alt tag

### CODE REVIEW

**Comment by Bramjetten** [comment]
Safari currently does not support document.registerElement right now. Any way we can fix this?

**Comment by acapro** [comment]
I added the polyfills from trix into another PR, supports Safari

**Comment by Bramjetten** [comment]
I edited the modal slightly to bring it more in line with the rest of our layout. Still looking for a nice way to change the image class.

**Comment by acapro** [comment]
Awsome!

**Comment by Bramjetten** [comment]
Btw, is it necessary to require the entire source of Trix?

**Comment by acapro** [comment]
Is it possible to overwrite class methods using $.extend? It would be a lot nicer that way, or maybe it  would make sense to branch out trix, modify it, and include the minified version of that. What do you think?

**Comment by Bramjetten** [comment]
Closing for now, but will revisit when Trix offers better extendability.

**Comment by daltonrenaldo** [comment]
@acapro this seems very useful, any update?

**Comment by Bramjetten** [comment]
@daltonrenaldo This was partially implemented in a recently merged PR. It's possible to add alt-text and a URL to images now.

**Comment by daltonrenaldo** [comment]
@Bramjetten you're correct. I decided to add to continue from that PR and add css classes. https://github.com/SpinaCMS/Spina/pull/509

**Pull request closed without merging**
